version: '3'
services:
    dev-client:
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        container_name: dev-client
        volumes:
            - /usr/src/app/node_modules
            - ./client:/usr/src/app

    application:
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "3001:3001"
        container_name: application
        depends_on:
            - db
        volumes:
            - /app/server/node_modules
            - ./server:/app/server

    db:
        image: 'mongo'
        container_name: MONGODB_MEDIUM
        ports:
            - '3002:3002'
        volumes:
            - ./data/db:/data/db