FROM node:14

WORKDIR /usr/src

COPY ./server/package*.json ./server/
COPY ./client/package*.json ./client/

RUN npm install --prefix ./client
RUN npm install --prefix ./server

ADD . .

EXPOSE 3001

CMD npm run start --prefix ./server
