version: '3'
services:
    dev-client:
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        container_name: dev-client
        volumes:
            - ./client:/usr/src/app

    application:
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "3001:3001"
        container_name: application
        volumes:
            - /app/client/node_modules
            - /app/server/node_modules
            - ./client:/app/client
            - ./server:/app/server
